export const pricingTiers = [
  {
    id: 'free',
    name: 'Free',
    price: '$0',
    period: 'forever',
    description: 'Perfect for getting started',
    features: [
      'Up to 3 products',
      'Basic analytics',
      'Email support',
      'Community access',
    ],
    cta: 'Get Started',
    highlighted: false,
  },
  {
    id: 'pro',
    name: 'Pro',
    price: '$29',
    period: 'per month',
    description: 'Best for growing businesses',
    features: [
      'Unlimited products',
      'Advanced analytics',
      'Priority support',
      'API access',
      'Custom integrations',
      'Team collaboration',
    ],
    cta: 'Start Free Trial',
    highlighted: true,
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: '$99',
    period: 'per month',
    description: 'For large-scale operations',
    features: [
      'Everything in Pro',
      'Dedicated account manager',
      'Custom SLA',
      'SSO authentication',
      'Advanced security',
      'White-label options',
      'On-premise deployment',
    ],
    cta: 'Contact Sales',
    highlighted: false,
  },
]
